server:
  port: 8081
  servlet:
    encoding:
      force-response: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: 1234qwer

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true